services:
  backend:
    container_name: luma-infisical-backend
    image: infisical/infisical:latest-postgres
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      db-migration:
        condition: service_completed_successfully
    env_file: .env
    environment:
      NODE_ENV: production
    ports:
      - "127.0.0.1:8080:8080"
    networks: [infisical]

  redis:
    container_name: luma-infisical-redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks: [infisical]

  db:
    container_name: luma-infisical-db
    image: postgres:14-alpine
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=$$POSTGRES_USER --dbname=$$POSTGRES_DB"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks: [infisical]

  db-migration:
    container_name: luma-infisical-db-migration
    image: infisical/infisical:latest-postgres
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    command: npm run migration:latest
    networks: [infisical]

volumes:
  postgres_data:
  redis_data:

networks:
  infisical:
